import type { Team } from '@world-cup/shared'

const fifaCodeToFlagCode: Record<string, string> = {
  ARG: 'ar',
  AUS: 'au',
  ALG: 'dz',
  AUT: 'at',
  BEL: 'be',
  BIH: 'ba',
  BOL: 'bo',
  BRA: 'br',
  CAN: 'ca',
  CHI: 'cl',
  CIV: 'ci',
  COD: 'cd',
  COL: 'co',
  CPV: 'cv',
  CRC: 'cr',
  CRO: 'hr',
  CUW: 'cw',
  CZE: 'cz',
  DEN: 'dk',
  ECU: 'ec',
  EGY: 'eg',
  ENG: 'gb-eng',
  ESP: 'es',
  FRA: 'fr',
  GER: 'de',
  GHA: 'gh',
  HAI: 'ht',
  IND: 'in',
  IRN: 'ir',
  IRQ: 'iq',
  ITA: 'it',
  JOR: 'jo',
  JPN: 'jp',
  KOR: 'kr',
  KSA: 'sa',
  MAR: 'ma',
  MEX: 'mx',
  NED: 'nl',
  NIR: 'gb-nir',
  NOR: 'no',
  NZL: 'nz',
  PAN: 'pa',
  PAR: 'py',
  PER: 'pe',
  POL: 'pl',
  POR: 'pt',
  QAT: 'qa',
  RSA: 'za',
  SCO: 'gb-sct',
  SEN: 'sn',
  SRB: 'rs',
  SUI: 'ch',
  SWE: 'se',
  TUN: 'tn',
  TUR: 'tr',
  UAE: 'ae',
  URU: 'uy',
  USA: 'us',
  UZB: 'uz',
  WAL: 'gb-wls',
}

export function getFlagSrc(team: Team): string {
  const flagCode = fifaCodeToFlagCode[team.fifaCode.toUpperCase()]

  return flagCode ? `/flags/${flagCode}.svg` : '/flags/un.svg'
}
